--------------------------------------------------------
--  File created - Friday-November-13-2015
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table IFSEXTENSIONS
--------------------------------------------------------

  CREATE TABLE "IFSTEST"."USERS"
   (	"EXTENSION" NUMBER(*,0),
	"USERNAME" VARCHAR2(20 BYTE),
	"FULLNAME" VARCHAR2(30 BYTE),
	"ADMIN" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

REM INSERTING into IFSTEST.IFSEXTENSIONS
SET DEFINE OFF;
Insert into IFSTEST.IFSEXTENSIONS (EXTENSION,USERNAME,FULLNAME,USERTYPE) values (1305,'gahlp','Aan de Silva','User');
Insert into IFSTEST.IFSEXTENSIONS (EXTENSION,USERNAME,FULLNAME,USERTYPE) values (1603,'abcdlk','Achala Bhagya','User');
Insert into IFSTEST.IFSEXTENSIONS (EXTENSION,USERNAME,FULLNAME,USERTYPE) values (6543,'namalk','Ajith Perara','User');
Insert into IFSTEST.IFSEXTENSIONS (EXTENSION,USERNAME,FULLNAME,USERTYPE) values (7832,'namalk','Ajith Perera','User');
Insert into IFSTEST.IFSEXTENSIONS (EXTENSION,USERNAME,FULLNAME,USERTYPE) values (0,'adminlk','Michelle','Admin');
Insert into IFSTEST.IFSEXTENSIONS (EXTENSION,USERNAME,FULLNAME,USERTYPE) values (8907,'surdlk','suchira','User');
Insert into IFSTEST.IFSEXTENSIONS (EXTENSION,USERNAME,FULLNAME,USERTYPE) values (5678,'prmdlk','promod','User');
Insert into IFSTEST.IFSEXTENSIONS (EXTENSION,USERNAME,FULLNAME,USERTYPE) values (8762,'abcdlk','Achala Bhagya','User');
Insert into IFSTEST.IFSEXTENSIONS (EXTENSION,USERNAME,FULLNAME,USERTYPE) values (5612,'namalk','Ajith Perera','User');
Insert into IFSTEST.IFSEXTENSIONS (EXTENSION,USERNAME,FULLNAME,USERTYPE) values (4009,'janlk','janitha','User');
Insert into IFSTEST.IFSEXTENSIONS (EXTENSION,USERNAME,FULLNAME,USERTYPE) values (3456,'pvpelk',' Pravinda Perera','User');
--------------------------------------------------------
--  DDL for Index IFSEXTENSIONS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IFSTEST"."IFSEXTENSIONS_PK" ON "IFSTEST"."IFSEXTENSIONS" ("EXTENSION", "USERNAME")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table IFSEXTENSIONS
--------------------------------------------------------

  ALTER TABLE "IFSTEST"."IFSEXTENSIONS" MODIFY ("EXTENSION" NOT NULL ENABLE);
  ALTER TABLE "IFSTEST"."IFSEXTENSIONS" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "IFSTEST"."IFSEXTENSIONS" MODIFY ("FULLNAME" NOT NULL ENABLE);
  ALTER TABLE "IFSTEST"."IFSEXTENSIONS" ADD CONSTRAINT "IFSEXTENSIONS_PK" PRIMARY KEY ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
