CREATE TABLE "USERS"
 (	"USERNAME" VARCHAR2(20 BYTE),
"FULLNAME" VARCHAR2(30 BYTE),
"ADMIN" VARCHAR2(20 BYTE),
CONSTRAINT USERNAME_pk PRIMARY KEY (USERNAME)
 ) SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "SYSTEM" ;

CREATE TABLE "EXTENSION"
 (	"EXTENSION" NUMBER(*,0),
"USERNAME" VARCHAR2(20 BYTE),
"CHANGED_USER" VARCHAR2(20 BYTE),
  CONSTRAINT USEREXTENSION_pk PRIMARY KEY (USERNAME,EXTENSION),
  CONSTRAINT fk_USERS
  FOREIGN KEY (USERNAME)
  REFERENCES  "USERS"(USERNAME)
 ) SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "SYSTEM" ;


CREATE table "temp"."EXTENSION" (

  USERNAME VARCHAR2(20 BYTE) NOT NULL,
  EXTENSION NUMBER NOT NULL,
  CHANGED_USER VARCHAR2(20 BYTE),
  CONSTRAINT USEREXTENSION_pk PRIMARY KEY (USERNAME,EXTENSION),
  CONSTRAINT fk_User
  FOREIGN KEY (USERNAME)
  REFERENCES User(USERS)

);

select (distinct)EXTENSION from EXTENSION e
  left join USERS u on e.USERNAME = u.USERNAME where u.full



  insert into IFSTEST.USERS values ('umchlk','umandya chandrasiri','umchlk')

    insert into IFSTEST.EXTENSION values (1236,'umchlk','umchlk')
